version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: etrifonoff/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: etrifonoff/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: etrifonoff/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
      - media:/media
