version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: etrifonoff/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/collected_static
      - media:/app/media

  frontend:
    image: etrifonoff/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: etrifonoff/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media
